# Generated by Django 3.1.7 on 2021-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credentials',
            field=models.JSONField(blank=True),
        ),
    ]
