# Generated by Django 3.1.7 on 2021-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210314_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
