# Generated by Django 3.2.2 on 2021-05-07 17:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_time_ranges',
            field=models.JSONField(default=core.models.default_day_time_ranges),
        ),
    ]
