# Generated by Django 3.2 on 2021-05-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('Taiga', 'Taiga'), ('Github', 'Github'), ('Mattermost', 'Mattermost')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('instance_url', models.URLField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubAuthFlow',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='github_auth', serialize=False, to='accounts.account')),
                ('state_parameter', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'tool', 'username', 'instance_url'), name='unique_account'),
        ),
    ]
