# Generated by Django 3.1.7 on 2021-03-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='instance_url',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='githubauthflow',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='github_auth', serialize=False, to='accounts.account'),
        ),
    ]
