# Generated by Django 3.2 on 2021-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'tool', 'username', 'instance_url'), name='unique_account'),
        ),
    ]
